name: Ejecutar Script Python y Crear PR

on:
  push:
    paths:
      - 'radar.csv'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Execute python script
        run: |
          python csv-to-json.py

      - name: Commit changes to main
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update radar-backstage.json"
          git push origin main
