name: Ejecutar Script Python y Crear PR

on:
  push:
    paths:
      - 'radar.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Execute python script
        run: |
          python csv-to-json.py

      - name: Commit updated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "master"
          commit_message: 'Update radar.csv and radar-backstage.json'
