name: Ejecutar Script Python y Crear PR

on:
  push:
    paths:
      - 'radar.csv'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Execute python script
        run: |
          python csv-to-json.py

      - name: Commit updated files
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.POC_TOKEN }}
          push-branch: "main"
          commit-message: 'Update radar.csv and radar-backstage.json'
          force-add: "true"
          force-push: "true"
